kind: Secret
apiVersion: v1
metadata:
  name: organization
  labels:
    spring.cloud.kubernetes.secret: "true"
data:
  spring.mongodb.password: UGlvdF8xMjM=
  spring.mongodb.username: cGlvdHI=
type: Opaque